### ISSUE TITLE
Generate markdown-compatible changelog?

### ISSUE THREAD

**Issue by jfcherng** [liip/RMT#138]
In [this readme section](https://github.com/liip/RMT/tree/a948dbdd9a2a2f0a6d5bd784010ff749819fe9dd#using-semantic-versioning-on-master-and-simple-versioning-on-topic-branches), there was 

```yaml
        changelog-update:
            format: semantic
            file: CHANGELOG.md
            dump-commits: true
```

But the generated .md file after rendering looks like the following.

![image](https://user-images.githubusercontent.com/6594915/42852876-998e77d6-8a65-11e8-8ecd-20fc2dc091b5.png)
