### ISSUE TITLE
How to increase command timeout

### ISSUE THREAD

**Issue by core23** [liip/RMT#144]
I have a problem when RMT tries to execute the `composer update` command:

```
In Process.php line 1236:

  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "composer update" exceeded the timeout of 60 seconds.
```

So how can I increase the timeout for a command?

My `.rmt.yml` config:

```yaml
vcs: git

prerequisites:
    - working-copy-check
    - display-last-changes
    - composer-json-check:
          composer: composer
    - command:
          cmd: composer update
    - tests-check:
          command: vendor/bin/phpunit --stop-on-failure
    - command:
          cmd: vendor/bin/phpstan analyse -c phpstan.neon -l 7 src tests
    - command:
          cmd: vendor/bin/php-cs-fixer fix --verbose
    - composer-security-check
    - composer-stability-check
    - command:
          cmd: vendor/bin/composer-require-checker check composer.json
          stop_on_error: false
    - command:
          cmd: git remote -v

pre-release-actions:
    composer-update: ~
    changelog-update:
        format: simple
        dump-commits: true
        exclude-merge-commits: true
    vcs-commit: ~

version-generator: semantic
version-persister: vcs-tag
```
