### ISSUE TITLE
Better YML config

### ISSUE THREAD

**Issue by jeanmonod** [liip/RMT#54]
Currently the YML config allow this:

```
vcs: git
```

and

```
vcs:
    name: git
    opt1: val1
```

Would be nice to also support the more standard version:

```
vcs:
    git: ~

vcs:
    git:
        opt1: val1
```
