### ISSUE TITLE
Configuration simplification

### ISSUE THREAD

**Issue by jeanmonod** [liip/RMT#56]
Seems that the "branch-specific" section is not that intuitive. A simplification could be to allow to type of config:

1) The simple one:

```
vcs: git
version-generator: semantic
version-persister: vcs-tag
```

2) The complex one, when you want custom branch settings

```
default:
    vcs: git
    version-generator: simple
    version-persister: vcs-tag
master:
    version-generator: semantic
```

Config parsing can switch to the complex mode as soon as there is a key "default" on first level.
