### ISSUE TITLE
Error "you must provide a [name] value"

### ISSUE THREAD

**Issue by sebastien-roch** [liip/RMT#68]
The following config make `RMT release` explode:

```
pre-release-actions:
    - "bin/ShellScriptLauncher.php":
        command: "app/console assets:install web --symlink --env=prod"
    - "bin/ShellScriptLauncher.php":
        command: "app/console assetic:dump --env=prod"
    - "changelog-update":
        format: semantic
    - vcs-commit
```

error:

```
[Liip\RMT\Config\Exception]                                                                     
  Config error: Missing information for [pre-release-actions_2], you must provide a [name] value
```

If I remove the `changelog-update` lines, it works. If I move the `changelog-update` to the top of the list, it works.
