### ISSUE TITLE
"name" Action option gets filtered out

### ISSUE THREAD

**Issue by ralf57** [liip/RMT#96]
```yaml
pre-release-actions:
  build-phar-package:
    name: my-package
    destination: foo
``` 
```php
// the 'name' options is filtered out
array(2) {
    'destination' => string(3) "foo"
}

// manually parsing the config via \Symfony\Component\Yaml\Parser() properly gets the 2 options
array(3) {
  'name' => string(9) "my-package"
  'destination' => string(3) "foo"
}
```
